name = "Imagilux"
license = "MIT"
description = "A clean and minimal Hugo theme for Imagilux"
homepage = "https://www.imagilux.org/"
demosite = "https://www.imagilux.org/"
tags = ["blog", "minimal", "clean", "responsive"]
features = ["blog", "responsive"]
min_version = "0.100.0"

[author]
  name = "k0bayashi"
  homepage = "https://www.imagilux.org/"
